### ISSUE TITLE
Errors with version 0.10.1 when not using AoT compilation

### ISSUE THREAD

**Issue by Cabeda** [telerik/kendo-angular2#107]
I've updated to angular-charts: 0.10.1 and I've tried to test it with the chart on [Chart Overview](http://www.telerik.com/kendo-angular-ui/components/charts/chart/) but it doesn't show any data.

I'm also using kendo-theme-default 1.31.0.

I'd love some help :-)

**Comment by tsvetomir** [comment]
What project template are you using? Is it generated using with ng-cli?

There's a known issue with the metadata that I'm currently investigating. Using `ng serve --aot true` should work for the moment. The other option is to downgrade to 0.9 at the moment.

**Comment by Cabeda** [comment]
Yes, I'm running with cli. The command worked. Should this issue stay open until it is completely resolved?

**Comment by tsvetomir** [comment]
Let's keep it open. I'll update it with our latest findings.

**Comment by tsvetomir** [comment]
Updated the title to reflect the problem more precisely. Errors look like:
`Can't bind to 'data' since it isn't a known property of 'kendo-chart-series-item'.`

**Comment by Cabeda** [comment]
I'm not sure if it's related because but the tooltips also stopped working and aren't being drawn in the DOM

**Comment by tsvetomir** [comment]
Very likely to be the same issue. Does it help if you reference 0.9?

**Comment by tsvetomir** [comment]
Can you give 0.10.2 a try? It should fix this issue.

**Comment by Cabeda** [comment]
As soon as I can I'll give it a try and give you an update

**Comment by Cabeda** [comment]
The first problem is resolved. I'm gonna look into the tooltip one now

**Comment by mike-waldrop** [comment]
I'm having the same issue regarding error:
Can't bind to 'data' since it isn't a known property of 'kendo-chart-series-item'.
I was using 0.13
I tried the solution in this thread by going back to 0.10 but am still getting the issue.  Please note that I'm not running inside cli but rather am using asp.net MVC with the appropriate node modules.  
Other kendo ui angular 2 controls work like tabs and grid, but chart is being incredibly stubborn.  the chart is nothing fancy.

<kendo-chart>
  <kendo-chart-title text="A Chart"></kendo-chart-title>
  <kendo-chart-series>
    <kendo-chart-series-item [data]="seriesData">
    </kendo-chart-series-item>
  </kendo-chart-series>
</kendo-chart>

If I add the CUSTOM_ELEMENTS_SCHEMA schema the error goes away but nothing renders except chart, title, scale.  No renders bars

If I don't add the CUSTOM_ELEMENTS_SCHEMA and take out the [data] attribute, error goes away and of course there's no chart data.  Essentially same as above.

I'm using systemjs.config.js if that helps.

been trying to figure this out for 3 days now.

**Comment by tsvetomir** [comment]
Version 0.12 of the chart and later require Angular 2.4.x as a peer dependency. See #175 

The reason is that we use inherited components, a feature not available earlier in Angular. See angular/angular#11606

**Comment by mike-waldrop** [comment]
Sorry for the late response.  I'm usually not so rude.  That fixed worked.  I had read about the 2.4 dependency but the error message i got never clicked with that fact.  A mistake on my part.  Your help was greatly appreciated.

**Comment by tsvetomir** [comment]
No offense taken. Peer dependencies are in a sad state, but unfortunately they're the only means to ensure a single copy of a given package is loaded.
